{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.scope.app_id }}
  namespace: {{ .Values.scope.environment_id }}
  labels:
    environmentId: {{ .Values.scope.environment_id }}
    appId: {{ .Values.scope.app_id }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.scope.app_id }}
  minReplicas: {{ .Values.autoscaling.min_instances }}
  maxReplicas: {{ .Values.autoscaling.max_instances }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.target_cpu_utilization_percentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.autoscaling.target_memory_utilization_percentage }}
{{- end }}