apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.scope.app_id }}
  namespace: {{ .Release.Namespace }}
  labels:
    environmentId: {{ .Values.scope.environment_id }}
    appId: {{ .Values.scope.app_id }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
    {{- if eq .Values.autoscaling.max_instances 1.0 }}
      maxSurge: 1
    {{- else }}
      maxSurge: 25%
      maxUnavailable: 10%
    {{- end }}
  {{- if eq .Values.autoscaling.enabled false }}
  replicas: 2
  {{- end }}
  selector:
    matchLabels:
      environmentId: {{ .Values.scope.environment_id }}
      appId: {{ .Values.scope.app_id }}
  template:
    metadata:
      labels:
        environmentId: {{ .Values.scope.environment_id }}
        appId: {{ .Values.scope.app_id }}
    # annotations:
    #   revision: {{ .Values.revision }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "appId"
                      operator: In
                      values:
                      - {{ .Values.scope.app_id }}
                topologyKey: "kubernetes.io/hostname"
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: {{ .Values.gracefull_shutdown_seconds }}
      securityContext: 
        runAsUser: 1001
        runAsGroup: 1001
        runAsNonRoot: true
        privileged: false
        allowPrivilegeEscalation: false
      containers:
        - name: {{ .Values.scope.app_id }}
          image: "{{ .Values.image }}:{{.Values.tag}}"
          imagePullPolicy: Always
          securityContext: 
            runAsUser: 1001
            runAsGroup: 1001
            runAsNonRoot: true
            privileged: false
            allowPrivilegeEscalation: false
          env:
            {{- range $secret := .Values.secrets }}
            - name: {{ $secret.key }}
              valueFrom:
                secretKeyRef:
                  name: "{{ $.Values.scope.app_id }}"
                  key: {{ $secret.key }}
            {{- end }}
          ports:
            {{- range $port := .Values.ports }}
            - name: {{ $port.name }}
              containerPort: {{ $port.target_port }}
              protocol: TCP
            {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.liveness.endpoint }}
              port: {{ .Values.liveness.port_name }}
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: {{ .Values.readiness.endpoint }}
              port: {{ .Values.readiness.port_name }}
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 1
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}Mi
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}Mi
          volumeMounts:
            {{- range $mounted_file := .Values.mounted_files }}
            - mountPath: "{{ $mounted_file.mount_path }}"
              subPath: content
              name: "{{ $mounted_file.id }}-{{ .Values.scope.app_id }}"
              readOnly: true
            {{- end }}
      volumes:
        {{- range $mounted_file := .Values.mounted_files }}
        - name: "{{ $mounted_file.id }}-{{ .Values.scope.app_id }}"
          secret:
            secretName: "{{ $mounted_file.id }}-{{ .Values.scope.app_id }}"
        {{- end }}

# SECURITY PRACTICES
#https://stackoverflow.com/questions/73358804/where-did-kubernetes-security-context-runasuser-1000-come-from
#https://www.cncf.io/blog/2020/10/16/hack-my-mis-configured-kubernetes-privileged-pods/
