{{- range $mounted_file := .Values.mounted_files }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $mounted_file.id }}-{{ .Values.scope.app_id }}"
  namespace: {{ .Release.Namespace }}
  labels:
    appId: {{ .Values.scope.app_id }}
    environmentId: {{ .Values.scope.environment_id }}
type: Opaque
data:
  content: |
    {{ $mounted_file.content }}
{{- end }}