apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.scope.app_id }}
  namespace: {{ .Values.scope.environment_id }}
  labels:
    environmentId: {{ .Values.scope.environment_id }}
    appId: {{ .Values.scope.app_id }}
type: Opaque
data:
  {{- range $secret := .Values.secrets }}
  {{ $secret.key }}: |-
    {{ $secret.value }}
  {{ end }}